docs/.vuepress/config.js, docs/how-tos/address-ipfs-on-web.md, docs/project/history.md
Also added internal pages for history (temporary) and web addressing (omitted 
earlier)
ref https://github.com/ipfs/docs/issues/345
=> Added external links to left nav menu items

docs/.vuepress/config.js, docs/.vuepress/theme/styles/index.styl, docs/.vuepress/theme/styles/palette.styl, docs/.vuepress/theme/styles/sidebar.styl, docs/.vuepress/theme/styles/video.styl, docs/essentials/file-systems.md, package-lock.json, package.json
=> configure markdown plugins and associated styling

README.md
Changed my username a couple of days ago. Now I'm going round updating all the `README.md` files. Super fun Friday afternoon activity.
=> Changed my username.

docs/.vuepress/theme/global-components/ContentStatus.vue
ref: https://github.com/ipfs/docs/issues/342
=> hack: hide edit links on content status pages

CONTRIBUTING.md
Pushed these changes to a personal public branch by accident. It just contains the contribution guidelines copied from `ipfs/docs master`.
=> Copied contribution guidelines from ipfs/docs repo.

docs/.vuepress/theme/components/Analytics.vue, docs/.vuepress/theme/components/Page.vue
=> feat: additional metrics

docs/.vuepress/theme/components/Page.vue, docs/.vuepress/theme/components/ScrollPatch.vue
=> fix: patch router scrolling on FF

docs/concepts/README.md
`How IPFS deals with Files` should be the first video as
`The lifecycle of Data in DWeb` is based on the concepts of Files.
=> Put the Videos from the IPFS Concept page in the right order

docs/how-to/address-ipfs-on-web.md
=> fix: IFPS → IPFS

docs/.vuepress/config.js, docs/.vuepress/theme/components/Analytics.vue, docs/.vuepress/theme/styles/header.styl
The IPFS docs you know and love, but with full text search thanks to the power of Algoia DocSearch! Now you can find aardvarks even if you can't spell aardvark correctly.
fixes: https://github.com/ipfs/docs/issues/336
=> feat: add Algolia DocSearch 🥳

docs/.vuepress/config.js, docs/.vuepress/theme/styles/index.styl, package.json
fixes: https://github.com/ipfs/docs/issues/429
@johnnymatthews let me know if this patch works. It means that FF will lose smooth scrolling but I feel that is the best workaround considering the inconstancies here.
=> fix: smooth scrolling

docs/concepts/merkle-dag.md
Did you find a bug, typo or other issue in an item of IPFS documentation? Please use this template to let us know!
**URL of the page in question:**
https://docs-beta.ipfs.io/concepts/merkle-dag/
**What's wrong with this page?**
Link to Juan's github returned a 404
**What would you like to have changed/amended/fixed in order to make things right?**
diff below fixes the link
**Would you be interested in helping fix this page?**
yup
**Is there any other feedback you'd like to share about IPFS docs?**
thanks for letting me join the video call. v2 docs look great!
=> update hsanjuan's github link

docs/.vuepress/theme/components/Page.vue, docs/.vuepress/theme/styles/index.styl
fixes: https://github.com/ipfs/docs/issues/435
=> fix: auto disable smooth-scroll on long pages

docs/how-to/command-line-quick-start.md
There were some `<pre>` and `<code>` tags in place of a markdown code-block. Removed and replaced with markdown syntax. There also a bunch of markdown syntax changes in here to reflect the rules in the [contribution rules](https://docs-beta.ipfs.io/community/contribute/grammar-formatting-and-style/#formatting). Finally, this page has been grammar and spell checked.
=> Removed hard-coded HTML, cleaned up markdown.

docs/README.md
Moved the 2nd sentence that _was_ in the intro paragraph into it's own <p> tags. The intro paragraph was a bit too long.
=> Shortened intro paragraph.

docs/.vuepress/config.js, docs/how-to/README.md, docs/how-to/browser-tools-frameworks.md
Bunch of broken `ipfs/js-ipfs` links fixed. Looks like the js-ipfs team moved their directories around.
=> Fixed broken js-ipfs links.

docs/concepts/how-ipfs-works.md
=> Maybe a typo?

docs/concepts/content-addressing.md
=> Added link to new ProtoSchool tutorial.

docs/.vuepress/config.js, docs/community/README.md
Updating to match our new leadership model
=> remove references to ProtoSchool chapters

docs/install/README.md
Optimize for developers installing IPFS (or IPFS Desktop), and then augmenting with IPFS Companion or Cluster
=> Reorder install page options

docs/reference/http/api.md
=> http reference: Fix more char escaping issues

docs/concepts/bitswap.md
Update to reflect Bitswap 1.2 changes
=> update bitswap concept doc for 1.2

docs/concepts/how-ipfs-works.md, docs/concepts/merkle-dag.md
Adds links to DAG Builder site in ...
- docs/concepts/how-ipfs-works.md
- docs/concepts/merkle-dag.md
Per Slack convo with @hsanjuan and @thattommyhall
=> Add links to DAG Builder

docs/.vuepress/config.js, docs/community/README.md
=> Adds newsletter signup link.

docs/concepts/README.md
These should be corrected now.
ref https://github.com/ipfs/docs/issues/526
=> Correct YouTube overview links in concepts/README.md

docs/concepts/README.md
Ref https://github.com/ipfs/docs/issues/526
Corrects issue identified by @cwaring in
Ref https://github.com/ipfs/ipfs-docs-v2/pull/213
=> Restore YouTube embeds

docs/.vuepress/theme/components/DeprecationNotice.vue
Changes legacy site deprecation date to 27th May.
=> Update deprecation date.

docs/install/command-line-quick-start.md, docs/recent-releases/go-ipfs-0-5/install.md, docs/recent-releases/go-ipfs-0-5/update-procedure.md
=> Update install and update instruction for 0.5.1

.circleci/config.yml, docs/.vuepress/config.js
updates: docs-beta.ipfs.io config and CI to use docs.ipfs.io
=> fix: domain url

docs/.vuepress/config.js, package-lock.json, package.json
fixes: https://github.com/ipfs/docs/issues/505
=> feat: add sitemap plugin and config

README.md, docs/community/contribute/grammar-formatting-and-style.md, docs/concepts/glossary.md
=> Removes word "beta" from docs

docs/.vuepress/theme/styles/index.styl
=> fix: logo svg scaling

docs/.vuepress/config.js, package-lock.json, package.json
closes https://github.com/ipfs/docs/issues/513
=> feat: add robots.txt

docs/.vuepress/config.js, docs/.vuepress/theme/styles/index.styl, docs/README.md, docs/community/README.md, docs/project/implementation-status.md, docs/recent-releases/go-ipfs-0-5/features.md, docs/reference/js/api.md
feat: add callout container
fix: links and remove issue from features
feat: complete implementation-status overhaul
=> feat: new callout, update implementation status and tweaks

docs/how-to/make-service.md
This PR is mainly to test that CircleCI is working properly. Also adds a couple links to the intro of _Make a Service_.
=> Adds links to Make a Service intro.

docs/.vuepress/config.js, docs/.vuepress/theme/global-components/ContentStatus.vue
=> Removed beta-test link.

docs/.vuepress/config.js, docs/.vuepress/theme/components/EditOrIssue.vue
=> Fixes the broken "Open issue link" for pages.

docs/concepts/immutability.md
Closes #264.
This page obviously isn't production ready yet, but I wanted to copy in the original post from @schomatis as a starting point. Everything in here will be re-written shortly.
=> Immutability page.

docs/reference/js/api.md
Adds a super exciting _call-to-action_ at the top of the JS-IPFS API section.
=> Adds ProtoSchool CTA.

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/open_an_issue.md
Adds the super handy welcome bot that all the other IPFS repos are using. Also removes links from Add Issue page.
=> Adds welcome bot!

docs/concepts/immutability.md
For some reason, 9169bf7 didn't get included in the #331 PR. This includes it.
=> Cherry picks a missing commit.

docs/how-to/configure-node.md
The link was broken..
Fixes #387
=> docs: update link to config file

docs/concepts/README.md
Adds OpenBazaar case study link to Concepts landing page.
=> Add OpenBazaar link

docs/project/history.md
Adds @gravenp's work on the [History of IPFS](https://github.com/gravenp/ipfs-docs-v2/blob/master/docs/project/history.md).
=> Adds Graven's copy.

docs/concepts/usage-ideas-examples.md
This implements the changes for issue #419.
=> Update use-cases page

CONTRIBUTING.md, docs/.vuepress/config.js, docs/community/contribute/contribution-tutorial.md
Found super old `ipfs-docs-v2` references lingering around. This PR removes them :)
=> Removes old repo refs.

docs/install/ipfs-companion.md, docs/install/ipfs-desktop.md
Noticed some capitalization inconsistencies on the Desktop and Companion install page; this PR fixes those. Also a few text tweaks on Companion install page for specificity.
cc @johnnymatthews 😊
=> Capitalize Desktop and Companion; a few text tweaks on Companion page

docs/concepts/usage-ideas-examples.md
=> Fixes typo.

docs/reference/http/api.md
Updated after running https://github.com/ipfs/http-api-docs/pull/34
=> update HTTP API docs for go-ipfs v0.7.0

docs/install/command-line.md
Urgh. I spelled _description_ wrong in the branch name. Lovely...
=> Adds description to command-line install.

docs/how-to/command-line-quick-start.md
Alyways, always, always check that links work before merging a branch...My own fault.
=> Fixes silly typo.

docs/install/ipfs-desktop.md
Options added, clarify where to get .deb
=> Ubuntu via snap and .deb install

docs/.vuepress/config.js
=> Collapse Latest Release in sidebar

docs/how-to/configure-node.md
=> Fixes "country" to "world" error.

docs/concepts/persistence.md
=> Spellcheck persistence.md

docs/.vuepress/theme/styles/alert-panels.styl, docs/.vuepress/theme/styles/index.styl
Originally created in #161, this PR was made so we can get previews from CircleCI. I could have made the previews manually, but it's Sunday and I'm feeling particularly lazy :smile:
=> Adds styles for alert panels.

docs/concepts/README.md
Add @aschmahmann's whiteboard overview of IPFS to Concepts landing page.
=> Add whiteboard video

docs/how-to/websites-on-ipfs/single-page-website.md
Also removed a couple of extra characters after the `</html>` tag. Published to https://ipfs.io/ipfs/Qmd1bJB1twKmMfzaAosfKGzyC2vyNVvdaGdEvgN76hj4fB?filename=index.html for review
=> ✏️ Fixed syntax errors in example index.html

docs/reference/cli.md, docs/reference/generate-cli-docs.sh
Closes #296 
Hello, So there is already a section in Http suggesting CLI is the same:
So added the same section to CLI (with minor changes):
=> Call out that the CLI and HTTP APIs are functionally the same.

docs/how-to/websites-on-ipfs/link-a-domain.md
=> Fixes issues in DNS Set up for Web Dev project.

docs/how-to/store-play-videos.md
Just got confused for a moment what `vidhash` was, so why not. Might change to something better if addressed/suggested.
=> Improves readability

docs/.vuepress/config.js, docs/how-to/make-service.md
I've lost few hours today to figure out what is wrong with my environment. It turns out the example is quite outdated.
Please, remove it or add a remark.
=> Hide "Make a service" from the sidebar.

docs/concepts/ipns.md
add a CLI example to https://docs.ipfs.io/concepts/ipns
=> Add IPNS CLI example

docs/.vuepress/config.js, docs/how-to/default-profile.md
---
* added details about what a profile is
* added a guide to find your active profile
* added docs for resetting your profile to default
=> Added documentation for inspecting and resetting ipfs default profile

docs/concepts/ipns.md
Duplicate of #592. Using this one because CI got stuck on the old PR.
=> Use promise instead of callback.

docs/concepts/ipns.md
Duplicate of #591 by @marc2332.
=> Fixes codeblock indentation.

docs/concepts/usage-ideas-examples.md
Remove info on RTrade hosted service -- cc @autonome for background.
=> Remove RTrade service info

docs/install/ipfs-desktop.md
Per https://github.com/ipfs-shipyard/ipfs-desktop/issues/691#issuecomment-766393622, minor changes to Desktop package managers list.
@johnnymatthews - please merge as part of your usual merge cadence!
=> Update package managers list on Desktop install page

docs/install/README.md
Now some browsers have IPFS support built-in it would be great to mention them.
=> Mention browsers that support IPFS.

docs/concepts/persistence.md
=> Fix a small typo

docs/how-to/use-existing-private-key.md
This PR re-adds a security section for private keys. For some reason, I removed this section from #568.
=> Re-adds security section for private keys,

docs/how-to/websites-on-ipfs/static-site-generators.md
=> Adds WordPress section to static-site generators.

docs/concepts/content-addressing.md
=> chore: fix formating

CONTRIBUTING.md, docs/community/contribute/grammar-formatting-and-style.md
How is this for issue #654 ?  I rewrote those sentences a few times and this is what I settled on, not sure if anything more needs to be said.
=> Add Project specific titles to contributing and grammar docs

docs/how-to/pin-files.md
=> Removes -r from unpin command.

docs/.vuepress/config.js, docs/how-to/best-practices-for-nft-data.md
This is an early draft of the NFT "best practices" documentation that we're working on. 
It's not ready for review yet (I'll be adding things over the weekend and Monday morning), but I'm putting it up as draft now for visibility, as I'm running out of steam for the day.
=> NFT best practices

docs/.vuepress/head.js
Similar to https://github.com/ipfs/ipfs-blog/issues/103
=> fix: add viewport meta to fix issue with firefox responsive mode

docs/.vuepress/config.js, package-lock.json, package.json
Adds [vuepress-plugin-chunkload-redirect](https://github.com/cwaring/vuepress-plugin-chunkload-redirect) to handle chunkload errors transparently.
=> feat: add vuepress-plugin-chunkload-redirect

docs/install/ipfs-desktop.md
This wording is similar to the Windows instructions, and provides a clickable link to the page we want them to go to.
I like clickable links.
=> add link to instructions step

docs/.vuepress/config.js, docs/.vuepress/plugins/vuepress-plugin-speedcurve/enhanceAppFiles.js, docs/.vuepress/plugins/vuepress-plugin-speedcurve/index.js
Partially addresses https://github.com/ipfs/ipfs-blog/issues/84
I've already added the `SPEEDCURVE_ID` env var to fleek.
=> Setup speedcurve plugin

docs/concepts/what-is-ipfs.md
=> Adds tip for Gateway.

docs/community/irc.md
=> Adds Matrix call-out.

docs/install/ipfs-desktop.md
=> Adds appimage install instructions.

docs/concepts/hashing.md
Hi @johnnymatthews,
this is my first draft for  [#430]. I decided to not add another hint on how input changes change the output of a has function as this is IMO not really related to the task at hand and already captured quite well in the existing documentation. Can you let me know if this generally goes into the right direction and what you would like to see improved / added? Thank you! 
Closes #430.
=> Explain why hashes are different between systems.

docs/how-to/websites-on-ipfs/link-a-domain.md
Fixes https://github.com/ipfs/ipfs-docs/issues/730
Included language suggested by @johnnymatthews as well as an example where I tried to show how much could be saved by increasing the number of years prepaid.
Result:
=> Updated the explanation of what goes into the cost for a domain

docs/install/ipfs-desktop.md
Using `brew cask install ipfs` doesn't work anymore, you need to do `brew install ipfs --cask`
=> Update hombrew command

docs/how-to/websites-on-ipfs/introducing-fleek.md
=> Fixes broken link.

docs/how-to/mint-nfts-with-ipfs.md
We are asked to create the txt file with the name flight-to-the-moon. There is no file called ticket.txt. 
I renamed and fixed it.
=> fixing the wrong file name

docs/.vuepress/theme/styles/index.styl, package-lock.json
=> Fixes code-block wrapping issue.

docs/how-to/best-practices-for-nft-data.md, docs/how-to/mint-nfts-with-ipfs.md
This PR adds references to NFT School on the following two pages, as requested in https://github.com/protocol/nft-website/issues/16:
- https://docs.ipfs.io/how-to/best-practices-for-nft-data/
- https://docs.ipfs.io/how-to/mint-nfts-with-ipfs/
=> Feat: add references to NFT School

README.md, docs/how-to/websites-on-ipfs/link-a-domain.md
Today I found out ENS uses ENS, and the Metamask+IPFS Companion duo seems to work fine so I added it while preserving the traditional method as an option.
Also deleted a seemingly left-over word and a typo from README.md
Best regards.
=> [how-to] Using ENS+IPFS to get an ENS domain (ciskip)

docs/install/ipfs-updater.md
1. Update ipfs-update to 1.7.1.
2. Update go-ipfs to 0.9.0.
=> fix: fix install doc versions

docs/README.md, docs/concepts/faq.md, docs/install/README.md, docs/install/ipfs-desktop.md, docs/install/ipfs-updater.md, docs/project/repository-guide.md
Just a few minor proofreading edits. Most of the stuff I was going to change, someone beat me to. :)
=> Proofreading

docs/reference/http/api.md
Didn't see this documented anywhere...
=> document boolean values

docs/how-to/websites-on-ipfs/single-page-website.md
=> Removes pinexplorer link. [ciskip]

docs/how-to/websites-on-ipfs/multipage-website.md
Changed command example path to preserve example consistency (multi-page-first-step)
=> preserve example consistency

docs/concepts/glossary.md
Slowly growing the Glossary. 
In this PR I've added some terms from sibling docs at https://ipld.io/glossary/
=> feat: add IPLD terms to the IPFS glossary

docs/concepts/ipns.md
=> Fixes old file-name typos.

docs/.vuepress/config.js
=> Fixes broken link to JS repo example.

docs/.vuepress/config.js, docs/concepts/nodes.md
This is a _prettifying_ of a [HackMD](https://hackmd.io/j1PQOmB3ReKEoMoQuN-tEg?view) put together by internal PL IPFS engineers and dev-rel folks.
It's pretty advanced as it stands right now, and could do with some simplifying for a more general reader. However, right now it serves a purpose.
=> Add types of nodes, and node implementations.

docs/concepts/ipns.md
The self key output is "Hello again IPFS" after being updated so I've
changed the "Make a change to your file, .." to reflect that.
=> Fix the output of updated file

docs/how-to/README.md, docs/how-to/browser-tools-frameworks.md, docs/how-to/create-simple-chat-app.md
=> Updates JS example links.

docs/install/command-line.md
Adds steps to help Windows users install IPFS using PowerShell.
Closes #940
=> Install IPFS using PowerShell.

docs/concepts/glossary.md
Making clear those are experiments, not full-fledged features
=> docs(glossary): filestore and urlstore

docs/install/command-line.md
Small edit changing the referenced version and download links from v0.10.0 to v0.11.0
=> Update version from v0.10.0 to v0.11.0

docs/how-to/command-line-quick-start.md
Added a couple lines about the UI/ Web console to tell how to view your ipfs file with it
=> Edited the section on command-line quickstart

docs/concepts/glossary.md
Added `AutoNAT` and fixed order in `A` section
=> docs(glossary): autonat

docs/concepts/glossary.md
Added `Multiaddr`  :see_no_evil:
=> docs(glossary): add multiaddr

docs/install/README.md
Sorry, I was thinking about the git process and didn't make the correct change. 
It should say, "A developer building network applications ... than someone who...."
=> Actually fixes typo.

docs/how-to/best-practices-for-nft-data.md
=> Fix typo in best-practices-for-nft-data.md

docs/concepts/README.md, docs/concepts/content-addressing.md, docs/concepts/file-systems.md, docs/concepts/ipns.md, docs/concepts/libp2p.md
added links in further resources as per https://github.com/ipfs/ipfs-docs/issues/893
Just links in the footnotes, and one in the videos section of Concepts.
=> Incorporate res net lab

docs/how-to/create-simple-chat-app.md
- added hyperlink for libp2p early in article
- recorded and added a .gif walking through the app with four browsers, gives reader quick overview of the app and keep engagement high
- added illustration of where status indicator is
- rewarded slightly in Docker section
=> Small improvements to Chat App tutorial

docs/concepts/ipns.md
Small change to terminology used when referencing the CID.
=> Change "Qm hash" to "CID"

docs/basics/README.md, docs/basics/desktop-app-basics.md
=> Beginners Guide to IPFS Desktop

docs/how-to/websites-on-ipfs/introducing-fleek.md
Corrected an omission. an alphabet was omitted from a word. Thereby making it incorrect.
The letter **r** was omitted from the word **service**
=> Docs: Corrected an omission made in "introducing-fleek.md"

docs/how-to/create-simple-chat-app.md
=> Revert "Fixes links, removes Docker, Meaningful titles"

docs/concepts/glossary.md
cc @olizilla @rvagg  – lmk  if  there are better resources/specs/explainers
=> glossary: add CAR

docs/how-to/peering-with-content-providers.md
Simple change to add the estuary addrs on the content-provider list.
=> chore: added estuary peer id

README.md
=> Adds troubleshooting section to the readme

docs/community/chat.md
Given the push to drive to docs.ipfs.io/community in https://github.com/ipfs/ipfs/issues/487, updated the chat information to be accurate as of 2022-07-08.
=> Update chat options for 202207

docs/basics/desktop-app.md
=> Fix typo in desktop-app.md

docs/how-to/peering-with-content-providers.md
Peer IDs and addresses of the IPFS nodes of the Storj IPFS pinning service.
=> add storj peer ids

docs/concepts/how-ipfs-works.md
https://github.com/ipld/specs/blob/master/block-layer/graphsync/graphsync.md 👉 https://github.com/ipld/ipld/blob/master/specs/transport/graphsync/index.md
=> Fix Graphsync URL

docs/concepts/privacy-and-encryption.md
=> Add Lit to list of encryption-based projects

docs/basics/ipfs-implementations.md
Adds a proper title and condenses introduction paragraphs.
=> Cleans up implementation page.

docs/how-to/peering-with-content-providers.md
We keep these up to date on our repos.
=> docs: link to authoritative peer listings for dotStorage

docs/how-to/host-git-repo.md
- plus some minor language fixes
=> host a git repo: change --bare to --mirror; rename (remove "style")

.github/actions/latest-kubo-tag/Dockerfile, .github/actions/update-with-latest-versions/Dockerfile
Related to https://github.com/ipfs/kubo/issues/9237
=> update Go version to 1.18

docs/.vuepress/theme/components/ScrollPatch.vue
=> Fix typo in ScrollPatch.vue

docs/concepts/immutability.md
- Follows the material in the linked issue to add information on how to address immutability pitfalls regarding CIDs.
- closes #908
Please view the latest Fleek preview [here](https://bafybeigfascxfnfvliyqn7d6u5qy62u5o4256dbqw3xzxjy7ztyl7gqn24.on.fleek.co/concepts/immutability/).
=> add: section on updating cids

docs/README.md
This was originally just a way to test if the PR template was working.
Anyway, this is still a valid PR that can be merged in. I figured, why not make this test a good PR anyway?
=> Small fix to the spelling of InterPlanetary File System

docs/install/server-infrastructure.md
Cosmetic stuff - Fixes markdown formatting, breaks out a few instructions into their own points, fixes issue with steps, makes minor tweaks to copy.
-  docs/install/server-infrastructure.md
-  Addresses most points on https://github.com/ipfs/ipfs-docs/issues/1356, other than the suggestion regarding copy
None
=> fix markdown formatting on /install/server-infrastructure/

docs/concepts/case-study-snapshot.md, docs/concepts/persistence.md, docs/how-to/create-simple-chat-app.md, docs/how-to/exchange-files-between-nodes.md, docs/how-to/websites-on-ipfs/link-a-domain.md
Fix more links, disable link check for links that arent actually links using the `` and `` markers
- docs/concepts/case-study-snapshot.md
- docs/how-to/create-simple-chat-app.md
- docs/how-to/exchange-files-between-nodes.md
- docs/how-to/websites-on-ipfs/link-a-domain.md
- docs/concepts/persistence.md
doesn't address an Issue, but does address link check GH action failure on https://github.com/ipfs/ipfs-docs/pull/1358. See output here https://github.com/ipfs/ipfs-docs/actions/runs/3714930371/jobs/6299476918
No
=> Random link fixes

docs/project/README.md
=> remove link to team management repo

docs/community/README.md
See https://blog.ipfs.tech/2023-01-ipfs-community-calendar/
=> Update link to community calendar

docs/concepts/persistence.md
Adding a "disclaimer" message above the list of available pinning services, noting that some of them are operated by third party companies. 
- docs/concepts/persistence.md
Issue #1392
=> Add disclaimer to list of pinning services

docs/how-to/nat-configuration.md
Addresses https://github.com/ipfs/ipfs-docs/issues/1424
docs/how-to/nat-configuration.md
https://github.com/ipfs/ipfs-docs/issues/1424
No
=> Update NAT config page to address https://github.com/ipfs/ipfs-docs/issues/1424

docs/how-to/peering-with-content-providers.md
docs/how-to/peering-with-content-providers.md
Addresses https://github.com/ipfs/ipfs-docs/issues/1394
No
=> Correct content in https://docs.ipfs.tech/how-to/peering-with-content-providers/

docs/install/server-infrastructure.md
Address https://github.com/ipfs/ipfs-docs/issues/1370
-  /install/server-infrastructure
https://github.com/ipfs/ipfs-docs/issues/1370
=> Refactor /install/server-infrastructure

docs/README.md
Changes to landing page definition of IPFS. Making it clear that IPFS is not a storage solution, and adding in a low-level definition of what IPFS is.
- docs/README.md
- Issue #1434 
No
=> Landing page - Rewrite IPFS definition

docs/README.md
Created this PR as a starting point for discussion regarding how we can refactor the landing page, which has come up multiple times.
=> Landing page revamp

docs/README.md, docs/concepts/README.md, docs/concepts/how-ipfs-works.md, docs/concepts/ipfs-solves.md, docs/concepts/what-is-ipfs.md
Gramatical fix.  "Comprised of" is not considered to be gramatically correct as "comprise" is already describing something that encompases other things and can generally be thought of as a synonym for "include".  This PR switches all instances of "comprised of" to "composed of".  "comprises" could alternatively be used instead.
Also one minor reword of "...how each one works" → "...how each one functions" to reduce repetition.
- docs/README.md
- docs/concepts/README.md
- docs/concepts/how-ipfs-works.md
- docs/concepts/ipfs-solves.md
- docs/concepts/what-is-ipfs.md
Hopefully no! :)
=> "comprised of" → "composed of"

docs/.vuepress/config.js, docs/reference/diagnostic-tools.md
Addresses https://github.com/ipfs/ipfs-docs/issues/1491
=> Adds page on diagnostic tools to reference

docs/concepts/how-ipfs-works.md
"can fetched" -> "can be fetched"
- 
- docs/concepts/how-ipfs-works.md
- 
- 
- 
- 
- 
-
=> Small correction in a passive sentence

docs/reference/diagnostic-tools.md
Adds phishing warning RE gateways, fixes missing link. Supersedes https://github.com/ipfs/ipfs-docs/pull/1535
=> Add phishing warning, fix link

docs/quickstart/publish_cli.md
`docs/quickstart/publish_cli.md`
Merged https://github.com/web3-storage/w3cli/blob/main/README.md with https://github.com/ipfs/ipfs-docs/pull/1490
From a convo with discordian: 
- Hard to say what the deadline should be, end of week or some point next week should be fine.
- I think this is p2, it's not mission critical (IMO, all the info is already in the README linked in the PR anyways)
Closes #1513
=> CLI publishing guide for w3

docs/.vuepress/config.js, docs/quickstart/publish_cli.md
Merges [Create Publish to IPFS with a CLI quickstart guide + docs review](https://github.com/ipfs/ipfs-docs/issues/1513) created by @TheDiscordian + @ElPaisano's initial edits
Finishes remaining edits, like adding the menu in
=> CLI publishing guide for w3 (#1548)

docs/.vuepress/config.js, docs/how-to/ipfs-updater.md, docs/install/command-line.md
Addresses https://github.com/ipfs/ipfs-docs/issues/1366
=> Update ipfs-update content

docs/reference/diagnostic-tools.md
This PR simplifies the introduction to the Diagnostic Tools page to use plain language.
docs/reference/diagnostic-tools.md
No issue
None
=> Plain language intro to Diagnostic Tools page

docs/how-to/peering-with-content-providers.md
Adds a disclaimer to the list of community created content providers.
https://bafybeifrlydrpu4s3ip3labgbc5aqnktc55moaizip5zidi2tnlszrc62m.on.fleek.co/how-to/peering-with-content-providers/#content-provider-list
=> Add content provider disclaimer

docs/community/README.md, docs/community/contribute/ways-to-contribute.md, docs/project/README.md
Same as   https://github.com/ipfs/ipfs-website/pull/142, part of https://github.com/protocol/bifrost-infra/issues/2018
=> chore: switch emails to .tech TLD

docs/concepts/persistence.md
PR adds Kriptonio pinning service to persistence.md document. Kriptonio is a Web3 development platform that offers IPFS pinning service.
- docs/concepts/persistence.md
Add new pinning service
No
=> add Kriptonio pinning service

docs/community/contribute/ways-to-contribute.md
=> Update ways-to-contribute.md fix typo

docs/community/contribute/grammar-formatting-and-style.md
=> Spelling fix: `core` → `code`

docs/concepts/how-ipfs-works.md
Address https://github.com/ipfs/ipfs-docs/issues/1578
=> Fix spec link

.github/workflows/vale.yml
https://filecoinproject.slack.com/archives/C03KLC57LKB/p1686680229440949
=> chore: update github actions

docs/concepts/how-ipfs-works.md
Just updating the wording of a few sentences I noticed while reading. 
- `docs/concepts/how-ipfs-works.md`
N/A
N/A
=> update wording in 'how-ipfs-works'

docs/.vuepress/config.js
- fix: resolve ERR_OSSL_EVP_UNSUPPORTED
=> fix: resolve ERR_OSSL_EVP_UNSUPPORTED

docs/concepts/further-reading/academic-papers.md
Added presentations made for European Open Science Cloud Symposium, describing IPFS as a prospective solution for decentralized data sharing and provenance.
- docs/concepts/further-reading/academic-papers.md
=> Added EOSC and ExPaNds.eu entries

docs/concepts/ipfs-gateway.md
HTTP-incompatible -> IPFS-incompatible
"HTTP-incompatible browsers, tools and software" doesn't make sense. Assuming it's a typo.
- docs/concepts/ipfs-gateway.md
None
None
=> fix typo: ipfs-gateway.md

docs/.vuepress/config.js, docs/how-to/webtransport.md
Address https://github.com/ipfs/ipfs-docs/issues/1286
=> Kubo and WebTransport

docs/.vuepress/config.js, docs/concepts/measuring.md
Address https://github.com/ipfs/ipfs-docs/issues/1698
=> Add ProbeLab page to Concepts

docs/concepts/persistence.md
Ensure that no service is favoured over another
=> sort pinning services alphabetically

docs/install/run-ipfs-inside-docker.md
Docker log is different now so I updated the expected output the user should expect to see.
`docs/install/run-ipfs-inside-docker.md`
Docker installation
=> Updated new output of docker log

docs/community/contribute/ways-to-contribute.md
- Remove links to archived repos
- Remove references to Protocol Labs-specific things
- Added Ecosystem directory link
ways-to-contribute.md
n/a
no
=> Remove stale content from ways-to-contribute.md

docs/.vuepress/config.js, docs/concepts/measuring.md
Originally #1699. Tried recreating PR because the Fleek GH action was not working, even after an empty commit. Sometimes, just creating a new branch works, but not this time
Address https://github.com/ipfs/ipfs-docs/issues/1698
=> Add ProbeLab page to Concepts (#1699)

docs/.vuepress/config.js, docs/concepts/cod.md
Addresses #1436 
Vale spell check is false-flag failing on words that are ok
=> Add CoD concepts section

docs/reference/kubo-rpc-cli.md
This PR updates Kubo RPC client list.
- Added correct one  for JS
- Added actively maintained one for .NET
=> chore: update kubo-rpc-cli.md

docs/reference/js/api.md
=> feat: mention verified-fetch

docs/how-to/peering-with-content-providers.md
Add bit.site Peer ID and Address
- 
- 
- 
- 
- 
- 
- 
-
=> Add bit.site Peer ID and Address

docs/quickstart/publish_cli.md
`w3 authorize <your@email.com>` -> `w3 login <your@email.com>`
=> fix: update w3 publish_cli.md

.github/workflows/build.yml
Add a workflow to build and deploy to Storacha using IPFS Deploy Action
=> ci: add workflow to deploy docs to storacha

docs/reference/kubo-rpc-cli.md
Remove dead PHP libraries and replace them with https://github.com/EdouardCourty/ipfs-php  (thx  @EdouardCourty)
=> docs: update kubo-rpc-cli.md
