ipfs/ipfs-docs

- docs/.vuepress/config.js
- docs/essentials/bitswap.md
- docs/essentials/content-addressing.md
- docs/essentials/dht.md
- docs/essentials/dnslink.md
- docs/essentials/faq.md
- docs/essentials/file-systems.md
- docs/essentials/hashing.md
- docs/essentials/how-ipfs-works.md
- docs/essentials/ipns.md
- docs/essentials/merkle-dags.md
- docs/essentials/persistence.md
- docs/essentials/what-is-ipfs.md
- docs/how-tos/command-line-quick-start.md
- docs/install/README.md
Resolved links and other problems in markdown files in the Essentials section of the site.
Remaining sections:
- Install IPFS
- How-tos
- API & CLI
- Support & community
- Project
> Resolved links in essentials .md files

- docs/essentials/README.md
- docs/essentials/bitswap.md
- docs/essentials/content-addressing.md
- docs/essentials/dht.md
- docs/essentials/file-systems.md
- docs/essentials/hashing.md
- docs/essentials/how-ipfs-works.md
- docs/essentials/immutability.md
- docs/essentials/merkle-dag.md
- docs/essentials/persistence.md
Incorporated the four core courses from IPFS Camp:
- Courses A and D are broad enough to touch multiple "essentials" topics, so added tip callouts to them in their respective topic pages, plus prompts in the top-level essentials page
- Courses B and C added to nav in the "How-tos" section
Ref https://github.com/ipfs/docs/issues/187
> Feat add corecourses

- docs/.vuepress/theme/global-components/ContentStatus.vue
- docs/essentials/bitswap.md
- docs/essentials/glossary.md
- docs/essentials/immutability.md
- docs/essentials/ipfs-gateway.md
- docs/essentials/ipld.md
- docs/essentials/libp2p.md
- docs/essentials/usage-ideas-examples.md
- docs/project/history.md
- Adds related links and associated GitHub issues to stub pages
- Pulls the preface content for issueNum in ContentStatus.vue so we can use full links there
This is one of two remaining pieces to close https://github.com/ipfs/docs/issues/342. The other is to remove "help us improve" link in the footer.
> Add related links to content stubs

- docs/.vuepress/config.js
- docs/.vuepress/theme/components/EditOrIssue.vue
- docs/.vuepress/theme/components/Page.vue
- Unlinks "on GitHub" in the feedback tool, which serves to visually separate the two links in this widget, so users can more easily distinguish them at a glance:
- Adds padding to the left side of the feedback tool and the legacy callout, in order to align them with the page content in desktop view:
@cwaring if you have time to further adjust (or ideally, 🍐code with me), these additional tweaks would improve the layout on the legacy callout. If not, we can merge and address later …
thx!
> Unlinks words and adjusts padding on two bottom-of-pg

- .circleci/config.yml
- docs/.vuepress/config.js
- docs/.vuepress/public-path.js
- package-lock.json
- package.json
This PR adds support for hosting in IPFS.
Steps:
`npx vuepress build docs`
`all-relative ./docs/.vuepress/dist`
`ipfs add ./docs/.vuepress/dist`
Enjoy.
Theres still a couple of assests in the public folder that all-relative doesn't handle but that should be easy to fix.
Working example https://ipfs.io/ipfs/Qmb3bTUHXuxcuU9VWB5yG99Usa826kw4ZagyZJ5DucSZo3/
> feat: support ipfs

- docs/.vuepress/config.js
- package-lock.json
- package.json
This PR adds `<link rel="canonical"` header ([rfc6596](https://tools.ietf.org/html/rfc6596), [Wikipedia](https://en.wikipedia.org/wiki/Canonical_link_element)) to deduplicate SEO across all copies loaded from various public IPFS gateways.
Prior Art:
- https://github.com/ipfs/distributed-wikipedia-mirror/issues/65
- https://github.com/vuejs/vuepress/issues/894
> fix: add canonical link

- docs/how-to/address-ipfs-on-web.md
This PR:
- adds a sample config to make it easier for people to run their own subdomain gateways before https://github.com/ipfs/go-ipfs/issues/6498 lands
- fixes tip/warning sections to use markdown extensions provided in vuepress 
- changes some header levels to improve search for "subdomain".
typing "subdo" in search field now shows the addressing subsection:
> ![search-subdomain-2020-01-09--20-03-46](https://user-images.githubusercontent.com/157609/72097613-08a01b00-331d-11ea-852f-ded7ded85661.png)
cc @autonome
> docs: subdomain gateways

- docs/concepts/glossary.md
https://github.com/ipfs/docs/issues/56
> Work on glossary.md

- docs/concepts/content-addressing.md
> Fix `mulit' typo in reference to `multihash'

- docs/how-to/README.md
All the [`js-ipfs`](https://github.com/ipfs/js-ipfs) links were borked. They moved their examples from `/examples` to `packages/ipfs/examples`.
> Fixing broken links.

- docs/recent-releases/go-ipfs-0-5/features.md
This adds short explainer about EthDNS
Based on what I remember + docs from https://eth.link/, feel free to edit as you wish. 
Ref.
- https://github.com/ipfs/go-ipfs/pull/6448
- https://github.com/ipfs/go-ipfs/pull/6700
cc'd @parkan (DRI for the EthDNS collab at the time) in case I messed it up :-)
> docs: EthDNS/eth.link support in go-ipfs 0.5

- docs/.vuepress/config.js
- docs/concepts/README.md
Adds a link to the IPFS primer ...
1. in the left-hand nav, in Concepts/IPFS 101
2. to the "IPFS 101" section of https://docs-beta.ipfs.io/concepts/
Note that this isn't perfect, because the IPFS primer itself contains more hands-on tutorials, but it's the most applicable place at present. In the longer term, we need to outsource/bounty-ize the remaining missing content in the IPFS primer, and then integrate that content as a whole either into the docs or ProtosSchool. See https://airtable.com/tbl21O1nXqFA7ADcT/viws9P58CvH333ZAW/recI3I40kyWLHXL6H for where this fits into our prioritized recommendations from the Q1 2020 ecosystem audit.
> Add IPFS Primer links

- docs/.vuepress/config.js
- docs/project/README.md
- docs/project/implementation-status.md
- docs/project/roadmap.md
Move the requirements (aka roadmap) and implementation status documents currently in the `ipfs/ipfs` repo into the docs, and update page links and side nav accordingly.
Disclaimer: This includes formatting for consistency, but not checking for updates and accuracy.
Ref https://github.com/ipfs/ipfs/pull/455
> Move content originally in ipfs/ipfs repo to docs

- docs/reference/http/api.md
It seems there were not API changes between 0.4.22 and 0.4.23
> HTTP reference for 0.4.23

- docs/concepts/dht.md
According to line 36, m is the number of bits, not the number of
combinations.
> Fix a mistake in docs/concepts/dht.md

- docs/recent-releases/go-ipfs-0-5/update-procedure.md
Replaces `0.5.0-rc1` with `0.5.0` in `go-ipfs-0-5/update-procedure.md`
(some automation in pre-commit hook also removed redundant whitespace)
> chore: fix version typos

- docs/how-to/address-ipfs-on-web.md
Now that go-ipfs 0.5.0 shipped, we should remove custon Nginx config snippet and point people at go-ipfs config and built-in features.
Preview: https://bafybeiflwen2vbmcbvh2zcuxhz4znmpc364tafs3jjn77w3sef6qmed4li.ipfs.dweb.link/how-to/address-ipfs-on-web/#subdomain-gateway
cc https://github.com/ipfs/ipfs/issues/337 https://github.com/ipfs/in-web-browsers/issues/89 @autonome @Stebalien @mburns
> Update notes about hosting own subdomain gateway

- docs/.vuepress/theme/components/DeprecationNotice.vue
- docs/.vuepress/theme/components/Page.vue
- docs/.vuepress/theme/global-components/ContentStatus.vue
Adds a deprecation notice to the top of every page, but it doesn't look great. Can't figure out how to get the warning message into the `content__default` div. 
@cwaring or @jessicaschilling, any ideas of how to throw it in there? I don't really want to spend more than 10 minutes on this if I can help it.
> Adds deprecation message into all pages.

- docs/how-to/companion-window-ipfs.md
The other library was superseded by ipfs-provider.
> fix: suggest ipfs-provider for  window.ipfs fallback

- docs/.vuepress/theme/components/LegacyCallout.vue
Edited the title text to remove the _beta_ notification. Also removed the _Become a tester_ link.
No doubt this could be reorganized to be prettier, but this does the job right now. Closes ipfs/docs#507
> fix: removes beta notification from footer.

- docs/how-to/command-line-quick-start.md
The Command-line quick start is in two different places for some reason. So /install/command-line-quick-start/ got updates, but how-to/command-line-quick-start/ was missed.
> Updates 0.5.0 to 0.5.1.

- docs/.vuepress/config.js
Algolia just migrated and deleted our old index, this connects to the new instance.
> fix: new docsearch index

- .circleci/config.yml
This is a quick fix that ensures both docs.ipfs.io and docs-beta.ipfs.io are updated at the same time and point at the same CID.
While we have redirects set up on Nginx, various pages still link to the beta site, and that means people loading page from local node see old version.
To illustrate, compare:
- http://docs.ipfs.io.ipns.localhost:8080/recent-releases/
- http://docs-beta.ipfs.io.ipns.localhost:8080/recent-releases/ (missing 0.6 release)
> fix: keep updating DNSLink at docs-beta.ipfs.io

- docs/concepts/file-systems.md
Closes issue [243](https://github.com/ipfs/ipfs-docs/issues/243)
Expanded the documentation by demonstrating how to use MFS, e.g. creating a directory, adding a file, removing a file and more. Also expanded the Unixfs section by:
- adding an example of a protobuf data format
- describing the importing and exporting functions
- adding additional resources.
> Expand MFS section of "File systems and IPFS" page

- docs/concepts/ipns.md
Before this commit, the docs claim that IPNS solves two problems: stable and human-readable names, but in fact in only solves the former. Currently the solution for human-readable names is DNSLINK.
> Do not claim that IPNS addresses are human-readable

- docs/how-to/websites-on-ipfs/link-a-domain.md
The single-dot link resolves to https://docs.ipfs.io/how-to/websites-on-ipfs/link-a-domain/introducing-fleek instead of the desired https://docs.ipfs.io/how-to/websites-on-ipfs/introducing-fleek/
> Fix Fleek link

- .circleci/config.yml
There's an ongoing issue with pushes to `master` not deploying. This PR changes the Docker image to `olizilla/ipfs-dns-deploy:debug` so that the devops folks can get a better look at what's going on.
> Changes Docker image to debug version.

- docs/.vuepress/config.js
- docs/how-to/README.md
Looks like the example was renamed last month: https://github.com/ipfs/js-ipfs/pull/3204
> Fix js-ipfs example link

- docs/how-to/command-line-quick-start.md
- docs/install/command-line.md
Pretty much a find and replace of 0.6.0 to 0.7.0 for Go-IPFS installations. Closes #463.
> Update install instructions to 0.7.0.

- docs/concepts/dht.md
- package.json
There is a bunch of interesting and useful information contained in the [Content Routing DHT deep dive blog post](https://blog.ipfs.io/2020-07-20-dht-deep-dive/). that hasn't made it into the docs yet. This PR fixes that.
> Updates DHT page with deep dive info.

- docs/how-to/address-ipfs-on-web.md
This PR aims to add better examples and clarify best practices around converting CID v0 to v1 for use in subdomains. 
It also mentions Base36 as a valid encoding in preparation for ED25519 libp2p-keys shipping with go-ipfs 0.7.0
cc https://github.com/ipfs/go-ipfs/pull/7441 @ipfs/wg-web-browsers
> Update Subdomain gateway section

- docs/how-to/command-line-quick-start.md
This link was going to GitHub for some reason. Fixed it so now it goes to the correct internal page.
> Updates external link to internal.

- docs/install/command-line.md
This matches the equivalent instructions for Linux users later in the file (L145).
I just want to be able to blindly copy instruction and Have It Work(TM).
> Add an explicit cd command to copypaste

- docs/how-to/websites-on-ipfs/static-site-generators.md
Previously the link pointed to Hugo's Quick Start
> Fix VuePress getting started link

- docs/.vuepress/config.js
- docs/community/README.md
- docs/concepts/content-addressing.md
- docs/concepts/file-systems.md
- docs/reference/js/api.md
This is an optimisation to reduce the number of redirects ProtoSchool users need to go through, but also a possible fix for the lower source traffic in ProtoSchool from docs.ipfs.io, which we will monitor over the following weeks.
After some time we will do another PR to add a main link in the homepage to ProtoSchool like @jessicaschilling suggested.
> Fix: Remove hashes from protoschool links (possible cause of mislabeled source in ProtoSchool Countyl stats)

- docs/install/ipfs-desktop.md
Closes #486 
Screenshots:
Added link below OS list:
Added a new sections which have the details from: 
[https://github.com/ipfs-shipyard/ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop)
> Package manager install options for IPFS Desktop

- docs/.vuepress/theme/styles/alert-panels.styl
- docs/.vuepress/theme/styles/index.styl
Closes [#402](https://github.com/ipfs/docs/issues/402).
As a side note, I think it makes more sense if note panels becomes info panels. Seeing as the beta only uses tips and notes, I think the styling would look better if tips and and notes look different.
> create stylesheet for alert-panels

- .circleci/config.yml
docs-beta is redirected to docs now, do you still need the old dnslink?
> remove docs-beta dnslink entry

- docs/concepts/dht.md
Replaced the single quote with a backtick and the formatting is restored
> docs: inline opened w/ single quote, should be backtick

- docs/how-to/use-existing-private-key.md
Add "use an existing private key" to the how-to section.
Fixes #386
> docs(how-to): add "use an existing private key"

- docs/concepts/privacy.md
The link to the Fleek case study is broken. If you go on [the docs](https://docs.ipfs.io/concepts/privacy/#encrypting-content-transported-via-ipfs) and click on the link `this case study on Fleek, a fast-growing IPFS file hosting and delivery service`, you will get a 404 error. This fixes it.
> Fix broken link

- docs/how-to/address-ipfs-on-web.md
This adds an example to "Protocol upgrade" section in our web addressing How-to.
> docs: add example to protocol upgrade

- docs/.vuepress/config.js
VuePress v1.8 now has the ability to customise the page suffix fixing inbound routing without JS enabled 🎉
ref: filecoin-project/filecoin-docs/pull/634
> feat: setup pageSuffix to remove .html links

- .circleci/config.yml
Every website build is sent to the collaborative cluster, but it should rather put those in the legacy cluster and only add the master builds into the collaborative one.
> Only pin master builds to collaborative cluster

- docs/.vuepress/config.js
fixes the incorrect master repo links as reported in #616.
closes: #616
> fix: change master to main for site config

- docs/install/command-line.md
Users who want to know how to install IPFS may not be aware of Snap's [confinement](https://snapcraft.io/docs/snap-confinement) behavior.  So, I thought it useful to add a note someplace where they might see it before they install the Ubuntu Snap package.
Hopefully, this can prevent issues like this one: https://github.com/ipfs/go-ipfs/issues/7872
> Add a note about Snap confinement

- docs/install/ipfs-companion.md
Removes beta channel info as beta sunsetted in https://github.com/ipfs-shipyard/ipfs-companion/pull/979.
cc @lidel
> Remove Companion beta info

- docs/install/ipfs-companion.md
This PR fixes a broken link on https://docs.ipfs.io/install/ipfs-companion/
> ![2021-02-10--23-20-47](https://user-images.githubusercontent.com/157609/107580307-a340ec80-6bf6-11eb-9cb9-db7cfca1214c.png)
> fix: ipfs-desktop link

- docs/how-to/command-line-quick-start.md
Just makes things a bit easier to read. Having something like `ipfs cat ipfs/Qm.../cat.jpg > cat.jpg` was a bit confusing, since the `cat` command looks like `cat.jpg`.
Closes #337
> Changings cat/jpg to spaceship-launch.jpg

- docs/how-to/configure-node.md
Adds the Go-IPFS node configuration options into the `how-to/customize-a-node` page. This isn't the best place for it, but it's the only logical place for config options to go _without_ re-configuring.
Closes #640.
> Copies config options from Go-IPFS repo.

- docs/how-to/command-line-quick-start.md
If you install ipfs-desktop (before go-ipfs) then "ipfs init" return
```bash
❯ ipfs init 
generating ED25519 keypair...done
peer identity: <peer identity>
initializing IPFS node at /home/<username>/.ipfs
Error: ipfs configuration file already exists!
Reinitializing would overwrite your keys.
```
not `/home/<username>/.go-ipfs` but `/home/<username>/.ipfs`
> fix local ~/.ipfs path

- docs/install/command-line.md
Cannot install with '--classic' since we publish snap as strictly confined
> For snap, do not suggest using --classic

- docs/concepts/dnslink.md
This PR removes vagueness around where TXT record should be located:
- Resolving TXT records on main name works only because it is supported for legacy reasons
- putting TXT record on  `_dnslink` it is both better for opsec and performance (no unrelated TXT results)
> docs: make it clear that _dnslink should be used

- docs/how-to/mint-nfts-with-ipfs.md
This changes the CIDs in the examples for the NFT minting guide to use CIDv1 instead of V0 (`bafy...` instead of `Qm...`), which plays nicer with web browsers and is generally what we want to recommend as "best practice".
@lidel made a [PR to minty](https://github.com/yusefnapora/minty/pull/13) to make the switch there that I just merged in, so this just makes the guide consistent with the code.
closes #707
> use CIDv1 in NFT guide

- docs/install/command-line.md
This is kind of inviting disaster. An IPFS node _usually_ takes less than 256 MiB of RAM, but I'd document 512 MiB to be safe.
> don't say that IPFS is light-weight

- docs/concepts/content-addressing.md
This PR fixes a broken link to the ProtoSchool Anatomy of a CID course.
> Fix broken link to ProtoSchool course

- docs/how-to/address-ipfs-on-web.md
Start the address-ipfs-on-the-web article with a clear recommendation for using https://ipfs.io/ipfs/<CID> when linking to content on IPFS.
Currently `ipfs add` still returns a cid v0, so it can't trivially be used in a subdomain, and many usecases (e.g NFTs) are not concerned about domain level security isolation as they point to media. They definitly dont want to be using ipfs:// scheme urls, as those only work in tools that are already ipfs aware.
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
> docs: add recommendation for ipfs.io/ipfs/CID

- docs/concepts/glossary.md
- docs/concepts/persistence.md
This PR aims to improve discoverability of docs related to local and remote pinning.
- The main goal is for user to discover guides specific to local and remote pinning when reading the explainer about persistence, permanence, and pinning. 
- Secondary goal is to remove proprietary pinning services and replace them with vendor-agnostic docs that promote `pin remote` commands added in go-ipfs 0.8.0
cc @ipfs/wg-pinning-services
> docs: update remote pinning guides

- docs/concepts/content-addressing.md
- docs/concepts/glossary.md
This PR adds basic docs about CID conversion (v0→v1, text→binary, and cid→hex).
Inspired by questions like https://github.com/multiformats/js-cid/issues/142
> docs: cid conversion

- docs/how-to/websites-on-ipfs/single-page-website.md
Made the download step consistent across all platforms. I noticed this first when looking at the macOS directions where it was pointing me to a nonexistent github repo to find the .dmg
> fix macOS download reference and make first step consistent

- docs/how-to/companion-x-ipfs-path-header.md
The page was lacking an example, this adds some.
> feat: add x-ipfs-path examples

- docs/how-to/best-practices-for-nft-data.md
This adds a recommendation to use CIDv1 for NFTs, along with a quick explanation of how to tell the difference and how to get v1 cids from `ipfs add`.
cc @autonome
> recommend CIDv1 in NFT best practices

- docs/.vuepress/config.js
- docs/how-to/peering-with-content-providers.md
This is a first pass at creating a list of nodes that "seed" a lot of IPFS content, to encourage gateway operators to peer with them.
I haven't had time to set up a JSON version - ideally it would be auto-generated so we only have one source of truth to edit in the future, but I haven't had time to set that up
Closes #754
cc @mikeal
> Add list of large content providers and info on peering

- docs/how-to/websites-on-ipfs/multipage-website.md
* Fix typo (`publich` -> `publish`)
* Fix broken link to "Check out the IPNS page to learn more"
> Fix typo and broken link

- docs/.vuepress/config.js
- docs/project/README.md
- docs/project/repository-guide.md
Adds a guide to the most common, important or frequently used repos in the IPFS org.
Closes #669. Supersedes https://github.com/ipfs/ipfs-docs/pull/670.
> Feat: create repo guide

- README.md
Hey @johnnymatthews -- this is the littlest fix of them all but didn't want to merge anything without your OK.
> Add explicit link to docs.ipfs.io at top of readme

- docs/how-to/command-line-quick-start.md
- docs/how-to/move-ipfs-installation.md
This adds a warning box to the cli quick start guide to advise against running ipfs commands with `sudo`. I also added a troubleshooting step to the "move ipfs installation" how-to guide, since it sounds like that's where people were hitting issues with this.
Closes #360
> Warn about using `sudo` & add troubleshooting info

- docs/welcome-builders.md
Minor updates for build.ipfs.io landing page:
- Link to ecosystem directory rather than raster logo parade
- Update video embed link
- Add link to NFT School
@johnnymatthews - the video that leads users to this page will go live imminently. Do you mind a quick look and a merge? Thank you!
> Content: update builders landing page

- docs/install/ipfs-desktop.md
"Ubuntu" with capital "U" does not scroll to the section. Hence changed
> Wrong case resulting in not scrolling.

- docs/reference/http/api.md
This PR adds response types that mirror the `Arguments` format, which include a description of each field
What the progress field does has been a bit of a mystery to us at @fission-codes (and everyone we've asked) for months. We eventually ran across this answer from `@Stebalien`
https://github.com/ipfs/go-ipfs/issues/7938#issuecomment-806336540
It would be good to have this in the docs rather than have to run across a response in a GitHub Issue.
If it's welcome, I would like to further contribute more detailed docs for the return type that includes things like optional return fields and descriptions. @fission-suite has been building deserializers by observing responses empirically and digging through the go-ipfs source.
Please let me know if this would be welcome
> Clarify progress response

- docs/project/contribute.md
Both links are archived / inactive, we moved to hosted services.
> fix: remove jenkins

- docs/concepts/ipns.md
in the example, the person makes a text file with "Hello IPFS".
so `ipfs cat` would return "Hello IPFS". currently there's an exclamation point that came from nowhere that I'm removing.
> remove erroneous exclamation point

- docs/install/ipfs-desktop.md
On Ubuntu (or other Ubuntu-based distros), when installing IPFS Desktop by AppImage the user does not have access to the command-line `ipfs` binary. This PR adds a warning about this limitation.
> Adds warning about AppImages lack of cmd-line.

- docs/concepts/README.md
- docs/concepts/privacy-and-encryption.md
Issue #948 states that the dweb-primer.ipfs.io site is down. While we work on getting it back up, I'm removing the links in this repo to that site.
> Removes 404ing links.

- docs/how-to/websites-on-ipfs/link-a-domain.md
This is a followup for https://github.com/ipfs/ipfs-docs/pull/906 which I missed at the time.
- We don't want our docs to promote Handshake-specific standard of `_contenthash`, which afaik does exactly the  same thing as pre-existing [DNSLink](https://dnslink.dev/) standard which was around for half of a decade :)
- My understanding is that Handshake does not care about specific name or format of TXT record, so it makes sense to rename the convention to use DNSLink, removing the need for introducing something new here.
- By switching to DNSlink here, the Handhake ecosystem gets the ability of being resolved on self-hosted IPFS gateways without any additional software (as noted in docs).
cc @johnnywu-namebase to make sure this change is fine with Handhake.
> docs: using dnslink in handshake docs

- docs/concepts/glossary.md
Added some things that we want to link to from Release Notes drafted in https://github.com/ipfs/go-ipfs/issues/8343 (but also useful on their own).
cc @vyzo @mxinden @marten-seemann for visibility – this adds some libp2p terms to the IPFS glossary at https://docs.ipfs.io/concepts/glossary, please eyeball in spare time in case I misrepresented anything.
> docs: glossary for go-ipfs 0.11 release notes

- .github/actions/update-on-new-ipfs-tag/entrypoint.sh
- .github/workflows/update-on-new-ipfs-tag.yml
@guseggert  the error was cosmetic – last step was running when it should not.
Fix from this PR skips it if there is no branch with updates.
> fix: proper noop when no http-api-updates

- docs/how-to/websites-on-ipfs/link-a-domain.md
Point to dnslink.io which explains what needs to be done in detail. We do not need to maintain duplicate docs for things.
Also the guide is wrong as it is. You cannot create a CNAME record for a root domain as it says. It needs to be an ALIAS record or an A record.
> Remove "Link a domain" DNS guide as it is wrong

- docs/how-to/move-ipfs-installation.md
We can't simply propose to use `--reflink=auto` always as MacOS doesn't support `auto`.
This reads the `cp --help` and add the `--reflink=auto` if `cp --help` contains `--reflink` and provide a subsential speed increase in linux that supports it.
> Move IPFS: Use autodectection of reflinking feature

- docs/README.md
- docs/community/chat.md
- docs/how-to/command-line-quick-start.md
As per https://github.com/protocol/docs/issues/9, replaces old and dull Slack and Matrix links with brand new and shiny Discord links.
> Replaces chat links with Discord.

- docs/concepts/immutability.md
The page about [Immutablility](https://docs.ipfs.io/concepts/immutability/) contains almost the same paragraph twice. I think this was added by mistake and I would argue it doesn't really added anything for the reader. However, you might want to keep it anyway.
With this PR, I'm suggesting to remove the duplicated paragraph keeping the more recent version (added in https://github.com/ipfs/ipfs-docs/commit/95fbcea4200353d256b660867ee001bb3c2d0b26). 
(It's kind of ironic that the change to the paragraph itself is of the style "hello world" -> "hello IPFS!")
> Remove duplicated info (ciskip)

- docs/README.md
> Added IPFS description and other UX tweaks

- docs/how-to/configure-node.md
- docs/how-to/default-profile.md
On Nodes.md, removed the list of nodes and gave a link to page with full definitions.
On the former default-profile.md I gave the full definition of each node. The title is a misnomer and confusing, so I changed it to Configure profile. Is there more to do to change the title? (Do we need to change the file name? Do I need to check for broken links? How can I do that?)
> ConfigNode:link;ConfigProfile:full def &newtitle

- docs/concepts/hashing.md
"Example" in the title makes it sound like it's an example of the section above it. It's not; it's stand-alone, so I removed the word "example."
In another PR, I had moved the bottom paragraph to the top of the article, so they knew why they were reading it, but I see that the original, now redundant, paragraph is left behind, so I removed it.
> Removes "Example" and redundant last paragraph

- docs/concepts/bitswap.md
The discovery paragraph had some Transfer information and the Transfer paragraph repeated some discovery information. Sorted them out.
Also, moved the last sentence from Discovery to the last sentence in Transfer to explain what happens if the transfer doesn't work.
> Removes discovery-transfer redundancies

- docs/install/command-line.md
- docs/install/ipfs-desktop.md
This PR is a correction to #1063, to which I mistakenly added a #1068  file. I will NEVER do that again (I hope).
In install > command-line.md:
- Adds Johnny's suggestions.  (except for the sentence: "The local daemon process is automatically started in the CLI with the command `ipfs daemon`." ...I realized they were talking about the actual command to run the daemon.)
- Divides long complex sentence into three.
- Clarifies that the second example (not on the Desktop) is in the CLI.
In install > ipfs-desktop.md:
fixes broken link
> Adds reviewers suggestions for CLI Nodes

- docs/concepts/ipns.md
For the explanation of K51, deleted initial space in paragraph, and added a comma after and and a period.
> Fixes typos in k51 explanation

- .github/actions/update-on-new-ipfs-tag/entrypoint.sh
- .github/workflows/update-on-new-ipfs-tag.yml
- docs/install/command-line.md
- Add a `current-ipfs-version` frontmatter option to make the feature opt-in,
- Add a search & replace on the ipfs tag.
> feat: auto update ipfs version in installation docs

- docs/concepts/glossary.md
For the Swarm entry: Removed the [More about Swarm addresses](../how-to/configure-node.md#addresses) link. The doc it links to has been removed.
> Removed Link in Swarm entry

- .github/actions/update-on-new-ipfs-tag/entrypoint.sh
- .github/dependabot.yml
- docs/install/command-line.md
This PR should fix automation that runs on new go-ipfs release:
- [fix: Syntax error: redirection unexpected](https://github.com/ipfs/ipfs-docs/commit/43068812a2a399b5d9f0d2a7bee524ee65374df4)
The `sh` provided by CI uses a different shell than bash, so `<<<` used below did not work ([CI failure](https://github.com/ipfs/ipfs-docs/runs/6116796964?check_suite_focus=true#step:5:20) - this should fix it.
https://github.com/ipfs/ipfs-docs/blob/b7aef5c8b4fc5e6efd46fe9e48b618f208353edb/.github/actions/update-on-new-ipfs-tag/entrypoint.sh#L35
- [fix: go-ipfs docs generation](https://github.com/ipfs/ipfs-docs/commit/9e5fa3c2096aecbf2d0afa1c8683cbd251c802eb)
Dependabot was updating go-ipfs dependency in `tools/http-api-docs/go.mod` (example: https://github.com/ipfs/ipfs-docs/pull/1109), which means …
> fix(ci): update on new go ipfs automation

- docs/README.md
The image sizing method doesn't work in the markdown parser. I removed it as the image size is correct and will fit perfectly in the table. It's displaying now.
> Fixing image display error in docs/README.md [styling bug]

- scripts/update-version-numbers.py
This script goes through each entry in the `pages_to_update` dictionary and grabs the respective latest version release from github API. Then, it searches and replaces the matching patterns in the corresponding docs page. (works for code blocks and paths). It stores the document along with the edits in `updated_page_content` and it has to close the file first before writing. This is to reset the pointer to the top of the file and so we can basically overwrite the whole file with the contents of `updated_page_content`.
> Edit for update-version script

- docs/how-to/peering-with-content-providers.md
Found a tiny typo in the [Peering with content providers](https://docs.ipfs.io/how-to/peering-with-content-providers/) doc.
> docs: Fix distributed hash table typo

- docs/concepts/glossary.md
+ changed related links to be more appropriate
cc @alanshaw @olizilla  who contributed to spec at https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md
> docs: add dnsaddr to glossary

- .github/actions/latest-ipfs-tag/entrypoint.sh
This will check the latest stable release, which will always do the right thing.
Old version assumed the latest tag without revision suffix is the latest release but it is not always the case (error prone).
For example, we now have 0.13, but:
```console
$ git clone https://github.com/ipfs/go-ipfs.git
$ cd go-ipfs
$ git describe --tags --abbrev=0
v0.12.2
$ git describe --tags
v0.12.2-506-gb36044be3
```
> fix: detect new go-ipfs tag using github releases

- .github/actions/update-with-latest-versions/entrypoint.sh
This fixes update-with-latest-versions script to follow github redirects
when a repo is renamed or moved across organizations.
Should fix problem described in https://github.com/ipfs/ipfs-docs/pull/1179#issuecomment-1163444989
(I also added some quotes so things are safer)
cc @laurentsenta @johnnymatthews  (just fyi)
> fix: renamed repos in update-with-latest-versions

- docs/concepts/usage-ideas-examples.md
The [Orion project](https://blog.setale.me/2020/12/06/So-long-and-thanks-for-all-the-fish-IPFS/) has been closed/disbanded/abandoned. This PR removes a paragraph talking about Orion.
Closes #1203.
> Removes Orion - project disbanded.

- docs/install/command-line.md
Found out the other day that when attempting to install on macos, running just `bash install.sh` will move the binary but return an error. Then if you attempt the install again using `sudo` it will return an error of `mv: ./ipfs: no such file or directory` because the first attempt already moved the binary. If this happens, users need to start from the beginning and re-download the binary, this time using `sudo`.
> Adds `sudo` to `bash install.sh` command

- docs/community/chat.md
Discord.com leads to a 404, should be Discord.gg/ipfs.
> Discord.com -> Discord.gg

- docs/.vuepress/theme/components/Page.vue
> Follow-up after #1220, part of https://github.com/protocol/bifrost-infra/issues/178
This adds URL normalization that will autocorrect .io to .tech across all gateway types.
`location.replace()` is used because to ensure replaced .io URL will not be saved in the browser history
> feat: redirect docs.ipfs.io → docs.ipfs.tech

- docs/community/chat.md
On the `Community/Chat` page, the Forums section was a normal header, made the page look weird. Changed to a subheader to be consistent with the rest of the page.
> Change Forums header to a Subheader

- docs/how-to/address-ipfs-on-web.md
- docs/how-to/default-profile.md
- docs/install/command-line.md
- docs/install/ipfs-updater.md
- docs/install/server-infrastructure.md
> Part of https://github.com/protocol/bifrost-infra/issues/2018
This PR replaces `dist.ipfs.io` with `dist.ipfs.tech`
> chore: switch to dist.ipfs.tech

- docs/how-to/run-ipfs-inside-docker.md
`https://github.com/ipfs-shipyard/kubo-docker-examples` points to a non-existent page.
> Fixed broken link (404)

- docs/how-to/websites-on-ipfs/static-site-generators.md
`relativeURLS` should be `relativeURLs` according to https://gohugo.io/content-management/urls/#relative-urls
> [Fixes] Update Hugo instruction

- netlify.toml
This explicitly sets the Netlify build config to fix builds:
- Sets the base directory correctly (so that Netlify can detect package.json, install dependencies and cache them properly)
- Sets the publish directory
> Add netlify build config

- docs/.vuepress/config.js
- docs/concepts/ipns.md
- package-lock.json
- package.json
This PR adds support for mermaid diagrams, already supported in github comments:
https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
Docs: https://mermaid-js.github.io/mermaid/
This PR adds two demo diagrams to IPNS docs:
>   ![Screenshot 2022-09-16 at 22-31-28 IPNS IPFS Docs](https://user-images.githubusercontent.com/157609/190728009-5a61b744-2fca-47e2-9068-5bf03f99e8f4.png)
>  ![Screenshot 2022-09-16 at 22-30-50 IPNS IPFS Docs](https://user-images.githubusercontent.com/157609/190728026-b64456ea-efea-4f73-9f01-c194c51c14c5.png)
> feat: add mermaid diagram support

- docs/install/ipfs-desktop.md
While going through https://docs.ipfs.tech/install/ipfs-desktop/, I noticed two busted links:
1) The link in the last sentence of the Windows install _The IPFS Desktop application has finished installing. You can now start to [add your site](https://docs.ipfs.tech/install/how-to/websites-on-ipfs/single-page-website/#add-your-site)._ returns a 404
2) The link in the last sentence of the Mac install _The IPFS Desktop application has finished installing. You can now start to [add your site](https://docs.ipfs.tech/install/ipfs-desktop/#add-your-site)._ doesn't go anywhere.
I'm guessing they were supposed to go to https://docs.ipfs.tech/how-to/websites-on-ipfs/single-page-website/ so I updated them accordingly. LMK if this is not the case.
> Fix links in IPFS desktop page

- docs/reference/js/api.md
Tracking issue: https://github.com/ipfs/js-kubo-rpc-client/issues/36
Parent issue: https://github.com/ipfs/js-kubo-rpc-client/issues/6
Originating issue: https://github.com/ipfs/kubo/issues/9125
This PR is intended to update the docs so that users will be pointed to `kubo-rpc-client` instead of `ipfs-http-client` when using Javascript/TypeScript to talk to Kubo.
fixes https://github.com/ipfs/js-kubo-rpc-client/issues/36
Things for reviewers to check:
1. Confirm I didn't miss any areas that should be updated (old mentions that should be updated that aren't yet)
2. Confirm the added information is accurate and desired
3. Confirm that the language used is aligned with maintainers' intentions
> docs: mention kubo-rpc-client

- docs/concepts/further-reading/academic-papers.md
- Adding publisher and year published to each of the papers listed in `academic-papers.md`.
- The first one, "IPFS - Content Addressed, Versioned, P2P File System" is simply listed as "Original IPFS white paper", as suggested in a comment from PR #1242.
- I researched the original publisher and date for each one as best I could, let me know if you notice that some information is incorrect.
- \docs\concepts\further-reading\academic-papers.md
- Issue #1247 
No.
> Adding publisher and year published to the papers.

- docs/concepts/ipfs-implementations.md
- docs/concepts/nodes.md
- docs/how-to/create-simple-chat-app.md
- docs/install/js-ipfs.md
- docs/project/repository-guide.md
- docs/reference/README.md
- docs/reference/js/api.md
Addresses https://github.com/ipfs/ipfs-docs/issues/1465 and [Part 1 of issue 1459](https://github.com/ipfs/ipfs-docs/issues/1459#issuecomment-1409131076)
> Add warning about js-ipfs being discontinued / point to Helia in a few places

- docs/project/repository-guide.md
Addresses https://github.com/ipfs/ipfs-docs/issues/1437
Initial updates to the page:
- In the **Protocol implementations** subsection
- Removed outdated https://github.com/rs-ipfs/rust-ipfs
- Added link to Helia repo w/ description that it's a pre-alpha implementation in JS 
1. I removed https://github.com/rs-ipfs/rust-ipfs from because it's in maintenance mode - is this correct thing to do? Assuming it's no longer an active project.
2. Do any of the other lists in the subsections need items added (missing, new, etc.) or removed (outdated, incorrect,  need to be elsewhere, etc.)
https://github.com/ipfs/ipfs-docs/pull/1446/files
> Update Repository Guide

- docs/.vuepress/theme/styles/index.styl
Addresses point 3 of https://github.com/ipfs/ipfs-docs/pull/1452#issuecomment-1412494112 -> basically a word bleed issue that occurs on mobile in the top bar menu that should be fixed regardless of the other changes being discussed in 1452 because it's an actual bug. 1452 was incorrectly scoped by me, so splitting work up this way
> Fix minor css word bleed issue in top menu

- docs/.vuepress/config.js
- docs/.vuepress/redirects
- docs/community/README.md
- docs/community/contribute/ways-to-contribute.md
- docs/how-to/command-line-quick-start.md
- docs/project/README.md
A second refactor of the Projects / Community section and sidebar menu. Addresses:
1. Restructures community page into different groups ->  https://bafybeibiyrgmm6xz4p3lyhhuyklzrqpojhjdni5422nrtkjedcxyunowse.on.fleek.co/community/
1. https://github.com/ipfs/ipfs-docs/issues/1469 adds a section getting dev support ->  https://bafybeibiyrgmm6xz4p3lyhhuyklzrqpojhjdni5422nrtkjedcxyunowse.on.fleek.co/community/#get-technical-support-and-help
1. Removes outdated community links (ProtoSchool isn't really a thing anymore, some repos in the main sidebar are no longer active) -> the Projects section sidebar and  https://bafybeibiyrgmm6xz4p3lyhhuyklzrqpojhjdni5422nrtkjedcxyunowse.on.fleek.co/community/
1. Shuffles sidebar menu items around 
1. Adds notes to a few pages about code of conduct and …
> community section update + add stuff about support

- .github/styles/pln-ignore.txt
We're getting a lot of spelling errors from the Vale GitHub action that does spell checks for `Helia`.
For example: https://github.com/ipfs/ipfs-docs/pull/1466/files#diff-ae2431aa520d47f48cd21d80f551e44f37dc9758528b68a572a4fefa025f95a4R41
Adds the word Helia to the list of ignored words by spell checker
> Add helia to ignored words

- .github/workflows/markdownlint-action.yml
- .markdownlint.jsonc
For the initial implementation, tried to configure the rules  to match https://docs.ipfs.tech/community/contribute/grammar-formatting-and-style/#style.
Rule definitions and descriptions are [here](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md)
The rule configuration is defined in `.markdownlint.jsonc`. Each rule has comments that describe whether or not it's already in the style guide / it's something we already enforce without defining it in the style guide / if it might be a good rule to enforce
**Todo:**
- Determine what other configurations the `markdownlint-action.yml `file should have
- Check that the config (`.markdownlint.jsonc`) actually matches https://docs.ipfs.tech/community/contribute/grammar-formatting-and-style/#style
- Run tests for each rule to make …
> Add Markdownlint Github action 

- docs/.vuepress/config.js
Removes markdown line breaks so the site doesn't render single newlines as line breaks. This will also allow the markdown syntax to be prettified.
docs/.vuepress/config.js
It was an internal suggestion I passed on that is addressed by this change request.
No
> chore: remove line breaks

- docs/.vuepress/config.js
- package-lock.json
- package.json
This is a hotfix PR that reverts the site back to using the default VuePress search. Algolia wasn't indexing the site properly, for some reason. We'll merge this PR while the team figures out what's going on with Algolia.
> Removes Algolia from docs.

- .markdownlint.json
- .markdownlint.jsonc
This file is left over from before my tine with PLN - looks like someone was using an older version of the markdownlint tool in the docs. We no longer use this file. The new file is `.markdownlint.jsonc`
> Delete legacy .markdownlint.json

- docs/concepts/dnslink.md
Cosmetics:
- We want to avoid using `ipfs.io` in examples, because it does too many things (it is a path gateway, but also happens to have a DNSLink, but it is a special-snowflake DNSLink specific to bifrost-infra and not the best thing to show people as a "simple example"
- Wikipedia is a safe choice, won't go anywhere, always resolvable
- http://dnslink.io → https://dnslink.dev
> fix: outdated links on dnslink page

- docs/concepts/content-addressing.md
Addresses https://github.com/ipfs/ipfs-docs/issues/1449
- Updates JS CID conversion code examples to v1
- Adds code sandbox section to embed example sandbox
> Update JS examples to v1, add code sandbox

- docs/.vuepress/config.js
- docs/concepts/ipfs-gateway.md
- docs/how-to/gateway-best-practices.md
- docs/how-to/gateway-troubleshooting.md
Incorporates some of the content from https://blog.ipfs.tech/2022-06-30-practical-explainer-ipfs-gateways-2/ into existing GW concepts and ref material 
Since the blog + the existing https://docs.ipfs.tech/concepts/ipfs-gateway/ page both have alot of contents, this PR:
- Prunes out best practice and troubleshooting type info from concepts/ipfs-gateway/
- Puts some best practices in /how-to/gateway-best-practices/
- Puts troubleshooting info in /how-to/gateway-troubleshooting/
> Update gateways info

- docs/how-to/peering-with-content-providers.md
Stages https://github.com/ipfs/ipfs-docs/pull/1546 because IMO, 1546 indicates that we should add a disclaimer, so this PR add a disclaimer to the content provider list before adding 1546.
> Add content provider warning / add EEC

- docs/how-to/websites-on-ipfs/redirects-and-custom-404s.md
https://github.com/ipfs/specs/blob/main/http-gateways/REDIRECTS_FILE.md points to https://specs.ipfs.tech/http-gateways/web-redirects-file/ now
> docs: _redirects specification link

- .github/workflows/close-empty-issue.yml
Adds https://github.com/rickstaa/empty-issues-closer-action to ipfs-docs.
Sidenote: 
I'm not clear on the best way to test GH actions before pushing to prod, so review / input is much appreciated 
Goal:
- Make triage cleaner and easier for docs team
- Automatically close all empty issues with note to author
- Help with spam issues
Todo:
> Adds GH action to auto close empty issue

- docs/concepts/usage-ideas-examples.md
Supersedes https://github.com/ipfs/ipfs-docs/pull/1585
What this PR does:
Adds entries for NIIIFTY and web3.storage requested in https://github.com/ipfs/ipfs-docs/pull/1585 as entries in `/concepts/usage-ideas-examples` instead of separate pages in `\how-to` (wrong place for this kind of content) as the original PR implemented. Also removes a few outdated entries IDed by busted links.
> Add new examples, prune old entries

- docs/how-to/troubleshooting.md
This is an appropriate fallout from the work to renaming go-ipfs to Kubo.
> Updated Kubo troubleshooting to not name squat

- docs/community/contribute/ways-to-contribute.md
Remove Community section which links back to the old ipfs/community repo which is dead
> Remove old link, content in https://docs.ipfs.tech/community/contribute/ways-to-contribute/#community

- .github/workflows/markdownlint-action.yml
- .github/workflows/update-on-new-ipfs-tag.yml
- [chore(deps): bump nosborn/github-action-markdown-cli from 3.2.0 to 3.3.0](https://github.com/ipfs/ipfs-docs/commit/8a0c4eff1acfcfaf131b356cae7842873ddca31e)
- [chore(deps): bump repo-sync/pull-request from 2.6.2 to 2.12.1](https://github.com/ipfs/ipfs-docs/commit/2dd47f81027de42381959b4409d29beab9bbec67)
> Dependabot updates

- docs/how-to/address-ipfs-on-web.md
Make clear that "daemon" is a Kubo daemon in https://docs.ipfs.tech/how-to/address-ipfs-on-web
> Updated address-ipfs-on-web to callout Kubo

- docs/how-to/companion-node-types.md
- docs/install/ipfs-companion.md
- Adds a deprecation notice for js-ipfs and provide a path forward.
- I am wondering if removing embedded node type as part of mv3 is a better option.
- https://github.com/ipfs/ipfs-companion/issues/1220 
- docs/how-to/companion-node-types.md 
- https://github.com/ipfs/js-ipfs/issues/4336
> fix: :wastebasket: Deprecation notice for js-ipfs

- docs/concepts/glossary.md
Simply takes the Glossary item for Peer Routing from [Libp2p](https://docs.libp2p.io/concepts/appendix/glossary/#peer-routing) and throws it into this repo.
> Adds glossary item for Peer Routing

- docs/reference/README.md
Update JavaScript section to remove confusing / outdated info
> Update JavaScript section to remove confusing / outdated info

- docs/concepts/libp2p.md
IPFS docs link to some libp2p concepts, but those links are broken after the libp2p docs refactor.
- docs/concepts/libp2p.md
- docs.libp2p.io had URL changes in 2022. It looks like some IPFS pages weren't updated.
No
> Update libp2p.md to account for docs.libp2p.io changes

- docs/concepts/dnslink.md
- docs/concepts/ipns.md
Per (very old) issue https://github.com/ipfs/ipfs-docs/issues/1158, we do not explicitly call out in the docs that IPNS names work with DNSLink. So, this PR makes minor updates to the following docs to make that more apparent:
- docs/concepts/dnslink.md
- docs/concepts/ipns.md
> 1158: Callout that IPNS names work with DNSLink

- docs/how-to/address-ipfs-on-web.md
This PR removes some legacy examples which predate subdomain gateways and native protocol handler work in Brave, and updates related paragraphs. 
Feel free to adjust phrasing if needed.
> docs: update address-ipfs-on-web.md

- docs/concepts/usage-ideas-examples.md
Addresses [1441: Add videos about apps from IPFS camp to the usage ideas & examples page to showcase advanced app architectures using IPFS](https://github.com/ipfs/ipfs-docs/issues/1441)
Examples added so far:
- Bluesky
- Tableland
- WebNative SDK
> 1441: Update usage ideas & examples page

- docs/concepts/ipfs-gateway.md
Add Best IPFS Gateway, a list of public gateway
-
> Add Best IPFS Gateway, a list of public gateway

- docs/install/ipfs-companion.md
- removed mention of Helia from `/install/ipfs-companion` page: it does not provide compatible Kubo RPC endpoint, nor gateway.
- updated some old links
> fix: remove incorrect companion prerequisite

- docs/concepts/dnslink.md
Remove suspicious \
The same dig command is present with and without "\". I think it looks suspicious. I've never seen a domain name start with \.
I just removed the bar.
no
> Extra "\" in dnslink.md

- docs/reference/js/api.md
Adding reference to helia.io.
- `docs/reference/js/api.md`
- Restructure references to js ipfs implementations.
- Not Applicable.
> feat(js): :recycle: Adding references to helia.io + Old js-ipfs stuff.

- docs/reference/kubo-rpc-cli.md
Now that https://github.com/ipfs/ipfs-docs/pull/1695 has been merged, and https://github.com/ipfs/ipfs-docs/issues/1194 closed, https://github.com/ipfs/ipfs-docs/issues/1194#issuecomment-1243483410 (previously https://github.com/ipfs/ipfs/pull/480) can be taken care of.
* `docs/reference/kubo-rpc-cli.md`
No.
> Add Scheme and Lua client libraries

- docs/how-to/webtransport.md
This is cosmetic, but IPFS Docs should not oversell on things that do not work today and/or are not related to IPFS at all.
Instead, I've added persistence to other IPFS nodes, such as pinning services (which works today).
> docs: clarify webtransport use cases for ipfs

- docs/concepts/glossary.md
- docs/concepts/nodes.md
> fix: update delegated routing docs

- docs/quickstart/publish.md
- docs/quickstart/publish_cli.md
Add a warning about outdated guides at a temporary measure until these are updated. The challenge is that currently signing up for web3.storage requires a credit card which isn't ideal for a quickstart
> chore: add warnings about outdated guides.

- .github/styles/pln-ignore.txt
- docs/.vuepress/config.js
- docs/concepts/ipfs-gateway.md
- docs/concepts/public-utilities.md
This PR adds a new page on public utilities infrastructure.
There's some nuance with the wording of who's operating the infra we need to get right. Would be good to hammer this out in this PR
> feat: add public utilities page

- .github/actions/latest-kubo-tag/Dockerfile
- .github/actions/update-with-latest-versions/Dockerfile
Updates Dockerfile to match Kubo's latest version.
> chore: update Dockerfile to Go 1.22

- docs/reference/kubo-rpc-cli.md
The referenced library is the core client.
Obviously there is nothing to test with this very simple commit.
> Add ExIPFS - an active rpc client

- docs/how-to/address-ipfs-on-web.md
- docs/install/ipfs-desktop.md
This was aspirational, but other systems did not engage on the idea, mostly due to technical and political limitation of a single piece of software having to act as a router.
Removing it to reduce cofusion. ipfs:// and ipns:// are the way we do things right now, incl. Brave (https://brave.com/ipfs-support/)
> chore: remove mentions of dweb:// URLs

- docs/how-to/peering-with-content-providers.md
- Stale and unresponsive peer IDs and multiaddresses have been removed from the list. These results were verified using DHT lookups and `vole libp2p identify` inspection.
- The Filebase multiaddress was added
- The list was alphabetically sorted
-  docs/how-to/peering-with-content-providers.md
IPFS Desktop and kubo users often attempt to peer with addresses on this list. This PR removes stale entries and ensures the currently listed entries are live.
It does not.
> Remove unresponsive content providers, update with new ones, and sort

- docs/install/README.md
Mentioning verified fetch at https://docs.ipfs.tech/install/, which is common entry point we send to people.
Preview: https://bafybeiaofkeqz22gktyvoykf2h3qpdshzcvogdc4zacfj4uf2rwubahu5e.on.fleek.co/install/
> docs: mention verified fetch

- docs/install/README.md
It seems this paragraph is a left-over from old version of the page introduced in https://github.com/ipfs/ipfs-docs/commit/10514163a34ee3a9d6e78eeeb9b610bd8d0ed2ab but no longer makes sense, especially in IPFS Desktop section, which has nothing to do with this, especially after [Estuary got shut down](https://github.com/ipfs/ipfs-website/issues/283).
Removing this sentence seems like the best course of action.
> fix: remove orphan paragraph

- docs/concepts/bitswap.md
- docs/concepts/glossary.md
This PR does not change content, just cleans page up by adding links to technical specification and fixing broken / outdated links.
> chore: cleanup bitswap page

- docs/how-to/nat-configuration.md
- docs/how-to/peering-with-content-providers.md
- docs/how-to/troubleshooting.md
Fixing some leftovers, I've seen people on forums still following outdated nat configuration tutorial.
Ref. 
- https://github.com/libp2p/go-libp2p/issues/2369
- https://discuss.ipfs.tech/t/getting-a-public-ip-behind-nat/18212/3?u=lidel
> chore: /quic → /quic-v1 in examples

- .github/styles/pln-ignore.txt
- docs/concepts/public-utilities.md
Given how much use and attention the public gateways provided by the IPFS Foundation get and how diverse IPFS implementations could be (https://specs.ipfs.tech/architecture/principles/#ipfs-implementation-requirements), it would be good to say explicitly what these public gateways support.
Information here is pretty rough but wanted to get something out. cc @darobin @lidel 
- docs/concepts/public-utilities.md
No
> feat: add information on the features supported by the public IPFS gateways

- docs/how-to/websites-on-ipfs/single-page-website.md
Just a language match between what's in IPFS desktop app and the documentation
- docs/how-to/websites-on-ipfs/single-page-website.md
- good documentation
- not from what I can tell
- [✅ ] Passing the beta version of the **Check Markdown links for modified files** check. Action results can be viewed [here](https://github.com/ipfs/ipfs-docs/actions/workflows/action.yml).
- [ ✅] Passing all required checks (The beta **Check Markdown links for modified files** check is not required)
> fix: match documentation with ipfs desktop button label

- docs/concepts/glossary.md
- **feat: add Mainnet to the glossary**
- **feat: add simpler explanation for CAR**
- IPFS Mainnet is a useful meme evident by the organic adoption of the term
- It's very useful for distinguishing between Iroh, experimental implementations and "Mainnet"
> Add IPFS "Mainnet" to the glossary 

- .github/styles/Vocab/ipfs-docs-vocab/accept.txt
- .github/styles/pln-ignore.txt
- docs/reference/diagnostic-tools.md
Add IPFS Check debugging guide video
> feat: add ipfs check video

- .github/styles/pln-ignore.txt
- docs/concepts/ipfs-gateway.md
> chore: add references to ipfs-gateway.md

- docs/reference/diagnostic-tools.md
Added glossary links + removed potential footguns.
> chore: update diagnostic-tools.md

- .github/styles/pln-ignore.txt
- docs/concepts/ipfs-implementations.md
- docs/how-to/address-ipfs-on-web.md
- docs/how-to/best-practices-for-nft-data.md
- docs/how-to/companion-node-types.md
- docs/how-to/companion-x-ipfs-path-header.md
- docs/install/README.md
- docs/install/command-line.md
Removed mentions of "Brave support" and updated some outdated content I noticed.
Context: https://blog.ipfs.tech/2024-brave-migration-guide/ cc @2color
> chore: brave cleanup + updated links

- docs/.vuepress/config.js
- docs/concepts/ipfs-implementations.md
- docs/install/README.md
- docs/install/server-infrastructure.md
Wanted to add missing-but-important "Mainnet" projects (Boxo, Rainbow, Someguy) to `/install` page, but realized the information architecture was pretty outdated and not very intuitive, so I've separated it into three sections:
1. User-Friendly Options
2. Command-Line & Infrastructure Tools
3. Software Development
This should make it easier for user visiting https://docs.ipfs.tech/install to make choice what to read, and what to skip + help ecosystem with people using Kubo for everything because they don't know better alternatives.
Updated various navigation and content links and applied minor fixes along the way.
cc @mishmosh @2color
> feat: cleaned up `/install` landing

- .github/actions/latest-kubo-tag/Dockerfile
- .github/actions/update-with-latest-versions/Dockerfile
- tools/http-api-docs/go.mod
Needed to fix build error:
```
github.com/ipfs/kubo@v0.31.0 requires go >= 1.23 (running go 1.22.8; GOTOOLCHAIN=local)
```
> chore: update Dockerfile to use go1.23

- docs/concepts/public-utilities.md
- Add new js-libp2p bootstrapper to public utilities
> feat: add new js-libp2p bootstrapper

- docs/how-to/troubleshooting.md
Fixed bad markup that I saw at https://docs.ipfs.tech/how-to/troubleshooting/#go-debugging - for example, the command won't run if you try to run it verbatim as it escapes to next line or whatever in Bash/shell:
```
$ curl localhost:5001/debug/pprof/profile > ipfs.cpuprof`
> 
> ^C
$
```
<s>BTW, I can't run the Kubo ipfs daemon anymore, it's stuck here for more than an hour
```
$ ipfs daemon
Initializing daemon... \ Kubo version: 0.30.0
Repo version: 16 \ System version: amd64/linux
Golang version: go1.22.7 \ PeerID: ...
2024/11/17 03:41:29 failed to sufficiently increase receive buffer size
(was: 208 kiB, wanted: 7168 kiB, got: 416 kiB).
See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
```
and never reaches "Daemon is ready". Maybe if I update Kubo that will fix …
> fix: troubleshooting.md

- docs/concepts/ipfs-gateway.md
- Clean up deprecated and unhelpful content
- Add recursive/non-recursive to gateway types
- Add trusted and trustless gateways to gateway types
> feat: rework gateway page and add recursive gateway

- .github/styles/Vocab/ipfs-docs-vocab/accept.txt
- .github/styles/pln-ignore.txt
- docs/concepts/ipfs-implementations.md
- Added Desktop Implementations section
- Added Content-Addressed Data section
- Removed "Tip" section
- Moved elastic-ipfs to Inactive section
implementations.md 
- Updates the Implementations list to (1) reflect emerging group of data-only IPFS implementations and (2) status changes for some projects.
No
> Update Implementations list

- .github/styles/Vocab/ipfs-docs-vocab/accept.txt
- docs/concepts/ipns.md
- docs/how-to/gateway-troubleshooting.md
- Update DHT expiration time to 48 hours
- Add analogy to Git in IPNS docs.
> correct dht expiration time and improve ipns docs

- .github/styles/pln-ignore.txt
- docs/concepts/lifecycle.md
Refine the lifecycle of data in IPFS page.
> refine the lifecycle page

- docs/concepts/ipns.md
Adds tips from https://discuss.ipfs.tech/t/ipns-best-setting-for-fast-update/18103/3?u=lidel to `docs/concepts/ipns`
> docs: ipns ttl tips

- docs/README.md
- docs/how-to/websites-on-ipfs/deploy-github-action.md
- docs/install/README.md
- **fix: name ipfs acronym on landing page**
- **small polish**
> Polish docs and add internal links

- .github/styles/pln-ignore.txt
- docs/concepts/public-utilities.md
> docs: clarify gateway feature set

- docs/how-to/work-with-pinning-services.md
I've removed Scaleway Labs from the list of pinning service providers.
The service has been discontinued: https://labs.scaleway.com/en/ipfs-pinning/#the-end
- docs/how-to/work-with-pinning-services.md
none
none
> remove Scaleway labs from list of providers

- docs/community/contribute/ways-to-contribute.md
- Fix broken link
- Added link to the ipfs/boxo repository in the contributions section
> Update ways-to-contribute.md with new repo link
